// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type XdpassGlobalCfg struct {
	_                      structs.HostLayout
	AllActiveRules         XdpassMaskT
	VlanOptionalRules      XdpassMaskT
	SrcPortOptionalRules   XdpassMaskT
	DstPortOptionalRules   XdpassMaskT
	SrcPrefixOptionalRules XdpassMaskT
	DstPrefixOptionalRules XdpassMaskT
	IngressVerdict         uint32
	_                      [4]byte
}

type XdpassIpv4LpmKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type XdpassMaskT struct {
	_    structs.HostLayout
	Bits [8]uint64
}

type XdpassRuleMeta struct {
	_            structs.HostLayout
	RuleId       uint32
	RequiredMask uint32
	Action       uint16
	Flags        uint8
	_            [1]byte
}

type XdpassTxConfig struct {
	_                      structs.HostLayout
	TcpResetMode           uint32
	TcpResetEgressIfindex  uint32
	TcpResetVlanMode       uint32
	TcpResetFailureVerdict uint32
}

// LoadXdpass returns the embedded CollectionSpec for Xdpass.
func LoadXdpass() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XdpassBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Xdpass: %w", err)
	}

	return spec, err
}

// LoadXdpassObjects loads Xdpass and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*XdpassObjects
//	*XdpassPrograms
//	*XdpassMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadXdpassObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadXdpass()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// XdpassSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpassSpecs struct {
	XdpassProgramSpecs
	XdpassMapSpecs
	XdpassVariableSpecs
}

// XdpassProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpassProgramSpecs struct {
	XdpassProg *ebpf.ProgramSpec `ebpf:"xdpass_prog"`
}

// XdpassMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpassMapSpecs struct {
	DstPortIndexMap *ebpf.MapSpec `ebpf:"dst_port_index_map"`
	DstPrefixLpmMap *ebpf.MapSpec `ebpf:"dst_prefix_lpm_map"`
	EventRingbuf    *ebpf.MapSpec `ebpf:"event_ringbuf"`
	GlobalCfgMap    *ebpf.MapSpec `ebpf:"global_cfg_map"`
	RuleIndexMap    *ebpf.MapSpec `ebpf:"rule_index_map"`
	SrcPortIndexMap *ebpf.MapSpec `ebpf:"src_port_index_map"`
	SrcPrefixLpmMap *ebpf.MapSpec `ebpf:"src_prefix_lpm_map"`
	StatsMap        *ebpf.MapSpec `ebpf:"stats_map"`
	TxConfigMap     *ebpf.MapSpec `ebpf:"tx_config_map"`
	VlanIndexMap    *ebpf.MapSpec `ebpf:"vlan_index_map"`
	XsksMap         *ebpf.MapSpec `ebpf:"xsks_map"`
}

// XdpassVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpassVariableSpecs struct {
}

// XdpassObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadXdpassObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpassObjects struct {
	XdpassPrograms
	XdpassMaps
	XdpassVariables
}

func (o *XdpassObjects) Close() error {
	return _XdpassClose(
		&o.XdpassPrograms,
		&o.XdpassMaps,
	)
}

// XdpassMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadXdpassObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpassMaps struct {
	DstPortIndexMap *ebpf.Map `ebpf:"dst_port_index_map"`
	DstPrefixLpmMap *ebpf.Map `ebpf:"dst_prefix_lpm_map"`
	EventRingbuf    *ebpf.Map `ebpf:"event_ringbuf"`
	GlobalCfgMap    *ebpf.Map `ebpf:"global_cfg_map"`
	RuleIndexMap    *ebpf.Map `ebpf:"rule_index_map"`
	SrcPortIndexMap *ebpf.Map `ebpf:"src_port_index_map"`
	SrcPrefixLpmMap *ebpf.Map `ebpf:"src_prefix_lpm_map"`
	StatsMap        *ebpf.Map `ebpf:"stats_map"`
	TxConfigMap     *ebpf.Map `ebpf:"tx_config_map"`
	VlanIndexMap    *ebpf.Map `ebpf:"vlan_index_map"`
	XsksMap         *ebpf.Map `ebpf:"xsks_map"`
}

func (m *XdpassMaps) Close() error {
	return _XdpassClose(
		m.DstPortIndexMap,
		m.DstPrefixLpmMap,
		m.EventRingbuf,
		m.GlobalCfgMap,
		m.RuleIndexMap,
		m.SrcPortIndexMap,
		m.SrcPrefixLpmMap,
		m.StatsMap,
		m.TxConfigMap,
		m.VlanIndexMap,
		m.XsksMap,
	)
}

// XdpassVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadXdpassObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpassVariables struct {
}

// XdpassPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadXdpassObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpassPrograms struct {
	XdpassProg *ebpf.Program `ebpf:"xdpass_prog"`
}

func (p *XdpassPrograms) Close() error {
	return _XdpassClose(
		p.XdpassProg,
	)
}

func _XdpassClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdpass_bpfel.o
var _XdpassBytes []byte
