name: xdpass build and release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  get-build-info:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag.outputs.VERSION }}

    steps:
      - name: Get build version
        id: tag
        run: echo "VERSION=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-latest
    needs: get-build-info
    env:
      VERSION: ${{ needs.get-build-info.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Build xdpass
        run: |
          bash scripts/build.sh

      - name: Pack
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          bash scripts/pack.sh
          mv build/xdpass.tar.gz build/xdpass-${{ needs.get-build-info.outputs.version }}.tar.gz

      - name: Upload Release Assets
        if: startsWith(github.ref, 'refs/tags/')
        id: upload_release_asset
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ needs.get-build-info.outputs.version }}
          file: build/xdpass-${{ needs.get-build-info.outputs.version }}.tar.gz
          overwrite: true
          file_glob: true